version: "3.8"
services:
  db:
    build: ./postgresql
    container_name: local_pgdb
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    volumes:
      - local_pgdata:/var/lib/postgresql
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    networks:
      - pgnet
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - pgnet
    depends_on: 
      - db
    links:
      - db
  phppgadmin:
    container_name: phppgadmin
    image: neimheadh/phppgadmin:latest
    ports:
      - "8090:80"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=myuser
      - POSTGRES_PASS=mypassword
    networks:
      - pgnet
    depends_on: 
      - db
    links:
      - db

volumes:
  local_pgdata:
  pgadmin-data:
  phppgadmin-data:

# Permite acomodar los contenedores en una misma red y que se puedan reconocer entre si
networks: 
  pgnet: 
    driver: bridge